version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5176:5176"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
